In [1]:
# Import library yang akan digunakan
# pandas digunakan untuk membaca dataset
# pathlib digunakan untuk mengelola path file

import pandas as pd
from pathlib import Path

In [2]:
# Menentukan lokasi project
# BASE_DIR = folder utama project
# RAW_DIR = folder tempat data mentah disimpan

BASE_DIR = Path.cwd().parent
RAW_DIR = BASE_DIR / "data" / "raw"

print(BASE_DIR)
print(RAW_DIR)

c:\Users\Project\skripsi\inflation-forecast-final
c:\Users\Project\skripsi\inflation-forecast-final\data\raw

In [3]:
# Melihat folder dataset yang tersedia

for folder in RAW_DIR.iterdir():
    print(folder.name)

BI-Rate
Exchange-Rate
Inflasi
Oil-Price

In [4]:
# Melihat file yang tersedia pada setiap folder

for folder in RAW_DIR.iterdir():

    print(f"\n=== {folder.name} ===")

    for file in folder.glob("*"):
        print(file.name)

=== BI-Rate ===
BI Rate, 2010.csv
BI Rate, 2011.csv
BI Rate, 2012.csv
BI Rate, 2013.csv
BI Rate, 2014.csv
BI Rate, 2015.csv
BI Rate, 2016.csv
BI Rate, 2017.csv
BI Rate, 2018.csv
BI Rate, 2019.csv
BI Rate, 2020.csv
BI Rate, 2021.csv
BI Rate, 2022.csv
BI Rate, 2023.csv
BI Rate, 2024.csv
BI Rate, 2025.csv

=== Exchange-Rate ===
CCUSMA02IDM618N.csv

=== Inflasi ===
Inflasi Bulanan (M-to-M), 2010.csv
Inflasi Bulanan (M-to-M), 2011.csv
Inflasi Bulanan (M-to-M), 2012.csv
Inflasi Bulanan (M-to-M), 2013.csv
Inflasi Bulanan (M-to-M), 2014.csv
Inflasi Bulanan (M-to-M), 2015.csv
Inflasi Bulanan (M-to-M), 2016.csv
Inflasi Bulanan (M-to-M), 2017.csv
Inflasi Bulanan (M-to-M), 2018.csv
Inflasi Bulanan (M-to-M), 2019.csv
Inflasi Bulanan (M-to-M), 2020.csv
Inflasi Bulanan (M-to-M), 2021.csv
Inflasi Bulanan (M-to-M), 2022.csv
Inflasi Bulanan (M-to-M), 2023.csv
Inflasi Bulanan (M-to-M), 2024.csv
Inflasi Bulanan (M-to-M), 2025.csv

=== Oil-Price ===
DCOILBRENTEU.csv

In [5]:
# Membaca contoh dataset inflasi tahun 2010

inflation_file = (
    RAW_DIR
    / "Inflasi"
    / "Inflasi Bulanan (M-to-M), 2010.csv"
)

inflation_df = pd.read_csv(inflation_file)

inflation_df.head()

,Kota Inflasi,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,Inflasi Bulanan (M-to-M) (Persen),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
3,KAB ACEH TENGAH,-,-,-,-,-,-,-,-,-,-,-,-,-
4,KOTA MEULABOH,-,-,-,-,-,-,-,-,-,-,-,-,-

In [6]:
# Menampilkan ukuran dataset
# shape = (jumlah baris, jumlah kolom)

inflation_df.shape

(155, 14)

In [7]:
# Menampilkan informasi dataset

inflation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Kota Inflasi  152 non-null    object
 1   Unnamed: 1    155 non-null    object
 2   Unnamed: 2    153 non-null    object
 3   Unnamed: 3    153 non-null    object
 4   Unnamed: 4    153 non-null    object
 5   Unnamed: 5    153 non-null    object
 6   Unnamed: 6    153 non-null    object
 7   Unnamed: 7    153 non-null    object
 8   Unnamed: 8    153 non-null    object
 9   Unnamed: 9    153 non-null    object
 10  Unnamed: 10   153 non-null    object
 11  Unnamed: 11   153 non-null    object
 12  Unnamed: 12   153 non-null    object
 13  Unnamed: 13   153 non-null    object
dtypes: object(14)
memory usage: 17.1+ KB

In [8]:
# Melihat nama kolom

inflation_df.columns.tolist()

['Kota Inflasi',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13']

In [9]:
# Melihat beberapa baris pertama

inflation_df.head(10)

,Kota Inflasi,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,Inflasi Bulanan (M-to-M) (Persen),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
3,KAB ACEH TENGAH,-,-,-,-,-,-,-,-,-,-,-,-,-
4,KOTA MEULABOH,-,-,-,-,-,-,-,-,-,-,-,-,-
5,KAB ACEH TAMIANG,-,-,-,-,-,-,-,-,-,-,-,-,-
6,KOTA BANDA ACEH,0.54,0.07,-0.16,-0.56,-0.07,0.3,1.13,-0.03,0.37,0.08,1.73,1.18,4.64
7,KOTA LHOKSEUMAWE,0.22,-0.23,-0.08,-0.74,0.01,1.91,0.92,0.42,-1.28,0.28,2.64,2.97,7.19
8,KAB LABUHANBATU,-,-,-,-,-,-,-,-,-,-,-,-,-
9,KAB KARO,-,-,-,-,-,-,-,-,-,-,-,-,-

In [10]:
# Melihat beberapa baris terakhir

inflation_df.tail(10)

,Kota Inflasi,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
145,MANOKWARI,0.17,-0.62,0.02,2.04,-1.61,1.18,1.9,0.45,-0.46,-0.85,-0.25,2.71,4.68
146,KAB SORONG,-,-,-,-,-,-,-,-,-,-,-,-,-
147,KAB SORONG SELATAN,-,-,-,-,-,-,-,-,-,-,-,-,-
148,KOTA SORONG,0.12,0.91,0.31,0.99,0.7,0.14,2.88,1.61,0.92,-0.05,0.67,-1.3,8.13
149,KOTA JAYAPURA,1.28,-0.52,0.56,-0.51,0.71,0.84,0.24,0.52,0.59,-1.52,0.37,1.87,4.48
150,MERAUKE,-,-,-,-,-,-,-,-,-,-,-,-,-
151,TIMIKA,-,-,-,-,-,-,-,-,-,-,-,-,-
152,KAB NABIRE,-,-,-,-,-,-,-,-,-,-,-,-,-
153,KAB JAYAWIJAYA,-,-,-,-,-,-,-,-,-,-,-,-,-
154,INDONESIA,0.84,-0.08,-0.14,0.15,0.29,0.97,1.57,0.76,0.44,0.06,0.6,0.92,6.96