In [1]:
# Library untuk membaca dan mengolah data

import pandas as pd
from pathlib import Path

In [2]:
# Menentukan lokasi folder project

BASE_DIR = Path.cwd().parent

RAW_DIR = BASE_DIR / "data" / "raw"
PROCESSED_DIR = BASE_DIR / "data" / "processed"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

In [4]:
# Mapping nama bulan Indonesia ke angka bulan

months = {
    "Januari": "01",
    "Februari": "02",
    "Maret": "03",
    "April": "04",
    "Mei": "05",
    "Juni": "06",
    "Juli": "07",
    "Agustus": "08",
    "September": "09",
    "Oktober": "10",
    "November": "11",
    "Desember": "12",
}

In [5]:
# Membaca data inflasi tahun 2010

file_path = (
    RAW_DIR
    / "Inflasi"
    / "Inflasi Bulanan (M-to-M), 2010.csv"
)

df = pd.read_csv(file_path)

df.head()

,Kota Inflasi,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,Inflasi Bulanan (M-to-M) (Persen),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
3,KAB ACEH TENGAH,-,-,-,-,-,-,-,-,-,-,-,-,-
4,KOTA MEULABOH,-,-,-,-,-,-,-,-,-,-,-,-,-

In [6]:
# Membaca data inflasi tahun 2010

file_path = (
    RAW_DIR
    / "Inflasi"
    / "Inflasi Bulanan (M-to-M), 2010.csv"
)

df = pd.read_csv(file_path)

df.head()

,Kota Inflasi,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,Inflasi Bulanan (M-to-M) (Persen),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
3,KAB ACEH TENGAH,-,-,-,-,-,-,-,-,-,-,-,-,-
4,KOTA MEULABOH,-,-,-,-,-,-,-,-,-,-,-,-,-

In [7]:
# Mengambil hanya data inflasi nasional Indonesia

indonesia_row = df[
    df.iloc[:, 0].astype(str)
    .str.contains("INDONESIA", case=False, na=False)
]

indonesia_row

,Kota Inflasi,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
154,INDONESIA,0.84,-0.08,-0.14,0.15,0.29,0.97,1.57,0.76,0.44,0.06,0.6,0.92,6.96

In [8]:
# Mengambil nama bulan
# Baris ke-2 berisi Januari sampai Desember

month_names = df.iloc[2, 1:13].tolist()

# Mengambil nilai inflasi Indonesia Januari sampai Desember

values = indonesia_row.iloc[0, 1:13].tolist()

print(month_names)
print(values)

['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember']
['0.84', '-0.08', '-0.14', '0.15', '0.29', '0.97', '1.57', '0.76', '0.44', '0.06', '0.6', '0.92']