In [1]:
# Import library yang dibutuhkan
# pandas digunakan untuk membaca dan mengolah data tabel
# pathlib digunakan untuk mengatur path folder/file

import pandas as pd
from pathlib import Path

In [2]:
# Menentukan lokasi folder project
# BASE_DIR = folder utama project
# RAW_DIR = folder tempat data mentah disimpan
# PROCESSED_DIR = folder tempat data hasil preprocessing disimpan
# BI_RATE_DIR = folder khusus data BI Rate

BASE_DIR = Path.cwd().parent

RAW_DIR = BASE_DIR / "data" / "raw"
PROCESSED_DIR = BASE_DIR / "data" / "processed"
BI_RATE_DIR = RAW_DIR / "BI-Rate"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("Base directory:", BASE_DIR)
print("BI Rate directory:", BI_RATE_DIR)

Base directory: c:\Users\Project\skripsi\inflation-forecast-final
BI Rate directory: c:\Users\Project\skripsi\inflation-forecast-final\data\raw\BI-Rate

In [3]:
# Melihat semua file BI Rate yang tersedia
# Tujuannya untuk memastikan file tahun 2010 sampai 2025 ada

for file in BI_RATE_DIR.glob("*"):
    print(file.name)

BI Rate, 2010.csv
BI Rate, 2011.csv
BI Rate, 2012.csv
BI Rate, 2013.csv
BI Rate, 2014.csv
BI Rate, 2015.csv
BI Rate, 2016.csv
BI Rate, 2017.csv
BI Rate, 2018.csv
BI Rate, 2019.csv
BI Rate, 2020.csv
BI Rate, 2021.csv
BI Rate, 2022.csv
BI Rate, 2023.csv
BI Rate, 2024.csv
BI Rate, 2025.csv

In [4]:
# Membaca satu file BI Rate terlebih dahulu
# Kita mulai dari tahun 2010 untuk memahami struktur datanya

file_path = BI_RATE_DIR / "BI Rate, 2010.csv"

bi_df = pd.read_csv(file_path)

bi_df.head()

,Variabel,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,BI Rate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
3,BI Rate,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5

In [5]:
# Melihat ukuran dataset
# shape = (jumlah baris, jumlah kolom)

bi_df.shape

(4, 14)

In [6]:
# Melihat nama kolom dataset BI Rate

bi_df.columns.tolist()

['Variabel',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13']

In [7]:
# Melihat beberapa baris awal untuk mengetahui letak nama bulan dan nilai BI Rate

bi_df.head(10)

,Variabel,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,BI Rate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
3,BI Rate,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5

In [8]:
# Mengambil nama bulan dari baris ke-2
# Kolom 1 sampai 12 berisi Januari sampai Desember
# Kolom 13 adalah Tahunan, jadi tidak digunakan

month_names = bi_df.iloc[2, 1:13].tolist()

# Mengambil nilai BI Rate dari baris ke-3
# Kolom 1 sampai 12 berisi nilai BI Rate bulanan

values = bi_df.iloc[3, 1:13].tolist()

print(month_names)
print(values)

['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember']
['6.5', '6.5', '6.5', '6.5', '6.5', '6.5', '6.5', '6.5', '6.5', '6.5', '6.5', '6.5']

In [11]:
# Mapping nama bulan Indonesia ke angka bulan
# Ini digunakan untuk membuat format tanggal standar

months = {
    "Januari": "01",
    "Februari": "02",
    "Maret": "03",
    "April": "04",
    "Mei": "05",
    "Juni": "06",
    "Juli": "07",
    "Agustus": "08",
    "September": "09",
    "Oktober": "10",
    "November": "11",
    "Desember": "12",
}

In [10]:
# Mengubah data BI Rate tahun 2010 menjadi format time series bulanan

year = 2010

bi_rate_2010 = pd.DataFrame({
    "date": [f"{year}-{months[month]}-01" for month in month_names],
    "bi_rate": values
})

# Mengubah tipe data date menjadi datetime
bi_rate_2010["date"] = pd.to_datetime(bi_rate_2010["date"])

# Mengubah BI Rate menjadi numeric
bi_rate_2010["bi_rate"] = pd.to_numeric(
    bi_rate_2010["bi_rate"],
    errors="coerce"
)

bi_rate_2010

         date  bi_rate
0  2010-01-01      6.5
1  2010-02-01      6.5
2  2010-03-01      6.5
3  2010-04-01      6.5
4  2010-05-01      6.5
5  2010-06-01      6.5
6  2010-07-01      6.5
7  2010-08-01      6.5
8  2010-09-01      6.5
9  2010-10-01      6.5
10 2010-11-01      6.5
11 2010-12-01      6.5

In [12]:
# Memastikan tipe data sudah benar
# date harus datetime
# bi_rate harus numeric/float

bi_rate_2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     12 non-null     datetime64[ns]
 1   bi_rate  12 non-null     float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 324.0 bytes

In [13]:
# Mengecek statistik ringkas BI Rate tahun 2010

bi_rate_2010.describe()

                      date  bi_rate
count                   12     12.0
mean   2010-06-16 12:00:00      6.5
min    2010-01-01 00:00:00      6.5
25%    2010-03-24 06:00:00      6.5
50%    2010-06-16 00:00:00      6.5
75%    2010-09-08 12:00:00      6.5
max    2010-12-01 00:00:00      6.5
std                    NaN      0.0

In [14]:
# Function untuk membangun dataset BI Rate per tahun
# Input: tahun
# Output: dataframe date dan bi_rate untuk 12 bulan pada tahun tersebut

def build_bi_rate_year(year):
    # Membaca file BI Rate berdasarkan tahun
    file_path = BI_RATE_DIR / f"BI Rate, {year}.csv"
    df = pd.read_csv(file_path)

    # Mengambil nama bulan dari baris ke-2
    month_names = df.iloc[2, 1:13].tolist()

    # Mengambil nilai BI Rate dari baris ke-3
    values = df.iloc[3, 1:13].tolist()

    # Mengubah format melebar menjadi format time series bulanan
    result = pd.DataFrame({
        "date": [f"{year}-{months[month]}-01" for month in month_names],
        "bi_rate": values
    })

    # Mengubah date menjadi datetime
    result["date"] = pd.to_datetime(result["date"])

    # Mengubah bi_rate menjadi angka
    result["bi_rate"] = pd.to_numeric(
        result["bi_rate"],
        errors="coerce"
    )

    return result

In [15]:
# Menguji function pada tahun 2015

build_bi_rate_year(2015)

         date  bi_rate
0  2015-01-01     7.75
1  2015-02-01     7.50
2  2015-03-01     7.50
3  2015-04-01     7.50
4  2015-05-01     7.50
5  2015-06-01     7.50
6  2015-07-01     7.50
7  2015-08-01     7.50
8  2015-09-01     7.50
9  2015-10-01     7.50
10 2015-11-01     7.50
11 2015-12-01     7.50

In [16]:
# Menggabungkan seluruh data BI Rate dari tahun 2010 sampai 2025
# Setiap file tahunan akan diproses dengan function build_bi_rate_year()
# Hasil akhirnya adalah satu dataset BI Rate bulanan

bi_rate_all = pd.concat(
    [
        build_bi_rate_year(year)
        for year in range(2010, 2026)
    ],
    ignore_index=True
)

bi_rate_all

          date  bi_rate
0   2010-01-01     6.50
1   2010-02-01     6.50
2   2010-03-01     6.50
3   2010-04-01     6.50
4   2010-05-01     6.50
..         ...      ...
187 2025-08-01     5.00
188 2025-09-01     4.75
189 2025-10-01     4.75
190 2025-11-01     4.75
191 2025-12-01     4.75

[192 rows x 2 columns]

In [17]:
# Mengecek ukuran dataset
# 2010 sampai 2025 = 16 tahun
# 16 tahun x 12 bulan = 192 baris

bi_rate_all.shape

(192, 2)

In [18]:
# Mengecek periode awal dan akhir data BI Rate

print(bi_rate_all["date"].min())
print(bi_rate_all["date"].max())

2010-01-01 00:00:00
2025-12-01 00:00:00

In [19]:
# Mengecek missing value pada dataset BI Rate

bi_rate_all.isnull().sum()

date       0
bi_rate    0
dtype: int64

In [20]:
# Mengecek apakah ada tanggal yang duplikat

bi_rate_all["date"].duplicated().sum()

np.int64(0)

In [21]:
# Menyimpan dataset BI Rate yang sudah rapi ke folder processed

output_path = PROCESSED_DIR / "bi_rate_monthly.csv"

bi_rate_all.to_csv(
    output_path,
    index=False
)

print(f"Dataset saved: {output_path}")

Dataset saved: c:\Users\Project\skripsi\inflation-forecast-final\data\processed\bi_rate_monthly.csv

In [22]:
# Membaca kembali file yang sudah disimpan
# Tujuannya untuk memastikan file berhasil dibuat dan isinya tetap aman

saved_bi_rate = pd.read_csv(PROCESSED_DIR / "bi_rate_monthly.csv")

saved_bi_rate.head()

         date  bi_rate
0  2010-01-01      6.5
1  2010-02-01      6.5
2  2010-03-01      6.5
3  2010-04-01      6.5
4  2010-05-01      6.5

In [23]:
# Mengecek ulang ukuran dataset yang sudah disimpan

saved_bi_rate.shape

(192, 2)