In [1]:
# Import library yang dibutuhkan
# pandas digunakan untuk membaca dan mengolah data tabel
# pathlib digunakan untuk mengatur path folder/file

import pandas as pd
from pathlib import Path

In [2]:
# Menentukan lokasi folder project
# BASE_DIR = folder utama project
# RAW_DIR = folder tempat data mentah disimpan
# PROCESSED_DIR = folder tempat data hasil preprocessing disimpan

BASE_DIR = Path.cwd().parent

RAW_DIR = BASE_DIR / "data" / "raw"
PROCESSED_DIR = BASE_DIR / "data" / "processed"

EXCHANGE_RATE_DIR = RAW_DIR / "Exchange-Rate"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("Base directory:", BASE_DIR)
print("Exchange Rate directory:", EXCHANGE_RATE_DIR)

Base directory: c:\Users\Project\skripsi\inflation-forecast-final
Exchange Rate directory: c:\Users\Project\skripsi\inflation-forecast-final\data\raw\Exchange-Rate

In [3]:
# Membaca dataset exchange rate dari FRED
# Dataset ini sudah berbentuk time series bulanan

file_path = EXCHANGE_RATE_DIR / "CCUSMA02IDM618N.csv"

exchange_df = pd.read_csv(file_path)

exchange_df.head()

  observation_date  CCUSMA02IDM618N
0       2010-01-01      9270.000000
1       2010-02-01      9326.250000
2       2010-03-01      9161.086957
3       2010-04-01      9026.318182
4       2010-05-01      9160.238095

In [4]:
# Mengecek ukuran dataset
# shape = (jumlah baris, jumlah kolom)

exchange_df.shape

(192, 2)

In [5]:
# Mengecek nama kolom dataset

exchange_df.columns.tolist()

['observation_date', 'CCUSMA02IDM618N']

In [6]:
# Mengecek informasi tipe data awal

exchange_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  192 non-null    object
 1   CCUSMA02IDM618N   192 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.1+ KB

In [7]:
# Membuat salinan dataset agar data asli tetap aman

exchange_rate = exchange_df.copy()

exchange_rate.head()

  observation_date  CCUSMA02IDM618N
0       2010-01-01      9270.000000
1       2010-02-01      9326.250000
2       2010-03-01      9161.086957
3       2010-04-01      9026.318182
4       2010-05-01      9160.238095

In [8]:
# Mengubah nama kolom agar lebih mudah dipahami
# observation_date -> date
# CCUSMA02IDM618N -> exchange_rate

exchange_rate = exchange_rate.rename(
    columns={
        "observation_date": "date",
        "CCUSMA02IDM618N": "exchange_rate"
    }
)

exchange_rate.head()

         date  exchange_rate
0  2010-01-01    9270.000000
1  2010-02-01    9326.250000
2  2010-03-01    9161.086957
3  2010-04-01    9026.318182
4  2010-05-01    9160.238095

In [9]:
# Mengubah kolom date menjadi datetime
# Mengubah exchange_rate menjadi numeric untuk memastikan nilainya angka

exchange_rate["date"] = pd.to_datetime(
    exchange_rate["date"],
    errors="coerce"
)

exchange_rate["exchange_rate"] = pd.to_numeric(
    exchange_rate["exchange_rate"],
    errors="coerce"
)

exchange_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           192 non-null    datetime64[ns]
 1   exchange_rate  192 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 3.1 KB

In [10]:
# Mengecek ukuran dataset
# Harusnya 192 baris dan 2 kolom

exchange_rate.shape

(192, 2)

In [11]:
# Mengecek periode awal dan akhir data

print(exchange_rate["date"].min())
print(exchange_rate["date"].max())

2010-01-01 00:00:00
2025-12-01 00:00:00

In [12]:
# Mengecek missing value

exchange_rate.isnull().sum()

date             0
exchange_rate    0
dtype: int64

In [13]:
# Mengecek apakah ada tanggal duplikat

exchange_rate["date"].duplicated().sum()

np.int64(0)

In [14]:
# Menyimpan dataset exchange rate yang sudah rapi ke folder processed

output_path = PROCESSED_DIR / "exchange_rate_monthly.csv"

exchange_rate.to_csv(
    output_path,
    index=False
)

print(f"Dataset saved: {output_path}")

Dataset saved: c:\Users\Project\skripsi\inflation-forecast-final\data\processed\exchange_rate_monthly.csv

In [15]:
# Menyimpan dataset exchange rate yang sudah rapi ke folder processed

output_path = PROCESSED_DIR / "exchange_rate_monthly.csv"

exchange_rate.to_csv(
    output_path,
    index=False
)

print(f"Dataset saved: {output_path}")

Dataset saved: c:\Users\Project\skripsi\inflation-forecast-final\data\processed\exchange_rate_monthly.csv

In [16]:
# Membaca kembali file yang sudah disimpan
# Tujuannya memastikan file berhasil dibuat dan isinya aman

saved_exchange_rate = pd.read_csv(
    PROCESSED_DIR / "exchange_rate_monthly.csv"
)

saved_exchange_rate.head()

         date  exchange_rate
0  2010-01-01    9270.000000
1  2010-02-01    9326.250000
2  2010-03-01    9161.086957
3  2010-04-01    9026.318182
4  2010-05-01    9160.238095